### ISSUE TITLE
Misleading error when resource type is unknown

### ISSUE THREAD

**Issue by ankon** [Collaborne/kubernetes-bootstrap#2]
~~~~
/home/andreas/project/collaborne/node_modules/kubernetes-bootstrap/src/bootstrap.js:302
							if (k8sClient.group(resource.apiVersion).resource(resource.kind).namespaced) {
							                                                                ^

TypeError: Cannot read property 'namespaced' of undefined
    at renderedContents.split.filter.map.reduce.forEach.document (/home/andreas/project/collaborne/node_modules/kubernetes-bootstrap/src/bootstrap.js:302:72)
    at Array.forEach (native)
    at /home/andreas/project/collaborne/node_modules/kubernetes-bootstrap/src/bootstrap.js:291:14
    at /home/andreas/project/collaborne/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:114:15)
~~~~

The actual problem here was a resource 'Deployment' with the wrong 'apiVersion'. The bootstrap tool should properly check that the resource exist and report that error.

**Comment by ankon** [comment]
This should have been fixed with https://github.com/Collaborne/kubernetes-bootstrap/commit/9626784e678d8411d2d96ed18150dbdcab369e73 already.
