### ISSUE TITLE
Applying fails with unhandled promise rejection "404 page not found"

### ISSUE THREAD

**Issue by ankon** [Collaborne/kubernetes-bootstrap#35]
~~~~
[2019-02-14T17:12:30.975] [INFO] kubernetes-bootstrap - aws.k8s.collaborne.com/v1.Role wip-production-201902-kafka-connect: smart failed: 404 page not found
(node:7777) UnhandledPromiseRejectionWarning: Error: Cannot apply resource aws.k8s.collaborne.com/v1.Role wip-production-201902-kafka-connect through 'smart'
    at applyResource (/home/travis/build/Collaborne/collaborne/node_modules/kubernetes-bootstrap/src/bootstrap.js:435:9)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:7777) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7777) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
~~~~

**Comment by ankon** [comment]
This particular one seems to be related to CRDs: For those we do not get the `reason` property of an error as `NotFound`, but rather as `Not Found`.
