### ISSUE TITLE
Applying a v1.List fails with "resourceVersion should not be set on objects to be created"

### ISSUE THREAD

**Issue by ankon** [Collaborne/kubernetes-bootstrap#36]
~~~~
[2019-02-14T21:59:39.711] [INFO] kubernetes-bootstrap - v1.Secret kube-lego-account: smart failed: resourceVersion should not be set on objects to be created
(node:7817) UnhandledPromiseRejectionWarning: Error: Cannot apply resource v1.Secret kube-lego-account through 'smart'
    at applyResource (/home/travis/build/Collaborne/collaborne/node_modules/kubernetes-bootstrap/src/bootstrap.js:441:9)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:7817) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7817) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
~~~~

(repeating for each element of the list)

**Comment by ankon** [comment]
Work-around: Convert the v1.List into a multi-document.

**Comment by ankon** [comment]
Actually that isn't the problem, but rather that the v1.List was made directly from `kubectl get -o yaml` -- which includes a bunch of things that we need to drop.
